In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('scores.csv')

In [4]:
len(df)

326

In [24]:
train = np.random.choice(326, round(326 * .8), replace=False)

In [34]:
np.savetxt('train.txt', train, delimiter=',', fmt='%d')

In [35]:
train

array([275, 272, 262, 233, 123, 179, 121, 159, 308,  50, 196, 280,  53,
       303, 185, 102,  18, 314, 108,  38, 253,   2, 136, 296,  96, 164,
        81, 301, 318, 111, 110, 153,  66, 267, 161,  55, 282,  44, 322,
         5, 277, 112, 214, 116, 243,   1, 106, 170,  67, 257, 244, 264,
        62, 271, 211, 323,  86, 194, 178, 254,  94, 208, 226, 192,  14,
        79, 298, 265, 134, 266, 270, 240, 219,  15,  84, 197, 151,  31,
       221, 118,  28,  11, 172, 127, 315,  85,  42, 313, 156,  58, 239,
        32, 203,  20, 163, 295, 173,  97,  12,  40, 160, 235, 231, 101,
       131, 147, 305, 241,  63, 145, 152, 288, 107,  88,  92, 215, 119,
       133, 287,  43, 260, 212, 204, 188,  75, 182, 218,  16,  89, 117,
       300,  51,  60, 224, 276, 189,  26, 284, 146,  45,  49,  30, 312,
        17, 273,  10, 166,  72, 132, 229, 175, 125, 306, 290,  90, 157,
       213,  52,   9,  76, 294, 138, 120, 210,  82,  56, 261, 130, 320,
       299, 195, 126,  61, 238,  21,  93, 181, 129, 278,  48,  8

In [76]:
a = np.fromfile('train.txt', sep ='\n').astype(int)

In [77]:
b = np.arange(326)
b[b not in a]

/Users/sjaffe/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  from ipykernel import kernelapp as app


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

65

array([  0,   1,   2,   5,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  20,  21,  23,  26,  27,  28,  30,  31,  32,  33,  34,
        35,  38,  39,  40,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 106, 107,
       108, 109, 110, 111, 112, 116, 117, 118, 119, 120, 121, 123, 125,
       126, 127, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 168, 170, 171,
       172, 173, 174, 175, 177, 178, 179, 181, 182, 183, 184, 185, 188,
       189, 190, 191, 192, 194, 195, 196, 197, 198, 200, 201, 202, 203,
       204, 205, 206, 208, 209, 210, 211, 212, 213, 214, 215, 21